parser: "@typescript-eslint/parser"

parserOptions: {
    "project": "./tsconfig.json"
}

plugins:
    - "@typescript-eslint"

extends:
    - "plugin:@typescript-eslint/recommended"

rules: {
    "@typescript-eslint/no-inferrable-types": "off"
}
