language: node_js

os: linux
dist: xenial

node_js:
    - 12
    - lts/*

notifications:
    email:
        on_success: never

script:
  - npm i -g codecov
  - npm i
  - npm test

after_success:
  - codecov
